### ISSUE TITLE
come up with a mapping between json paths and fields for the detail views

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/viecpro-nuxt#33]
For frontend development we need to have a mapping between the json data and the detail views.
In a first step come up with a csv that contains entity type, json path, field label and data type.

**Comment by gregorpirgie** [comment]
After some discussions and careful consideration, the following solution is currently being tested: 

Background:
The mapping was needed, as there where complex transformations from several requests in the frontend-detail pages in which the individual request's data where re-arranged to fit the expected sections in the frontend. This resulted from a mismatch between the generic backend-datamodel and the display in the frontend. The underlying issue of the missmatch  can not be solved in itself, as we can't change the underlying datamodel, as the project is in its final stage.

To mitigate this underlying issue, we decided to: 

- move the transformation logic from frontend to backend
- provide a datastructure that contains for each instance of each entity all data that is needed for the detail page of this instance
- serve this datastructure in a simple way

After discussing the issue with Robin and looking at the state of his implementation, the best solution to deliver this datastructure was: 

- I created a new collection viecpro_detail_person which is structured to contain for each person instance all data needed for the detail page
- I provided Robin with the full schema of the new collection plus an explicit mapping of the nested objects within this schema, so this is now the mapping that this issue asked for. 
 
Robin tests this implementation now, if it works and eases the further development, I will implement the same logic for the other entities with detail pages. 

If this implementation causes other issues with Typesense, I will move the datastructure from a collection in Typesense to a REST endpoint and serve it from there. I coded it in a way so that the datastructure can be served from both, Typesense or REST without a need to change the mapping (i.e. the structure itself and all the types within this structure).

We decided against implementing the latter (REST-Endpoint) right away, as serving the detail page from typesense better suits the implementation that Robin has been working on and is the path of least resistance.

I will close the issue when the tests are finished and the implementation is decided on.
