### ISSUE TITLE
facet counts are wrong and need to be updated

### ISSUE THREAD

**Issue by sennierer** [acdh-oeaw/viecpro-nuxt#63]
if you are searching for a name and select a facet afterwards the counts of the facets are not updated. Eg [search for "Franz" and select facet "Kanzlist"](https://viecpro-frontend.acdh-ch-dev.oeaw.ac.at/de/search/persons?q=Franz&page=1&facets=functions:=[`Kanzlist`]).
The facet says it will return 115 results, but we get actually (according to pagination) 91 and the counts of the other facets are not updated (eg ' male' still says 2735 results, although it should be 115 or less)

**Comment by kaggl** [comment]
Facet counts are not wrong per se, many people in the database where Kanzlists multiple times at different times (see https://viecpro-frontend.acdh-ch-dev.oeaw.ac.at/de/detail/persons/325128). Typesense counts every instance of this torwards the Kanzlist counter, so one person can count as multiple kanzlist for typesense.

Since "functions" is a generated field, it should be possible to remove any duplicates and fix this issue.

ive created an issue here: acdh-oeaw/viecpro-backend-devops#36
