### ISSUE TITLE
nuxt-content mermaid render problems

### ISSUE THREAD

**Issue by gregorpirgie** [acdh-oeaw/viecpro-nuxt#7]
Description: 

- mermaid blocks in markdown are now rendered
- but the spacing is off, the diagram is vertically squashed

ToDo:
- fix rendering issue 
- rendering is dependent on playwright, which is locally installed
    - needs to be installed in docker env also

**Comment by kaggl** [comment]
I seem to have found the problem here: Somewhere during conversion, all  hyphens get dropped, so some attributes do literally nothing because they have the wrong names, see attached images (top is hyphenless attributes, bottom is the fixed equivalent that looks as intended)
![Screenshot_20230816_150936](https://github.com/acdh-oeaw/viecpro-nuxt/assets/48437174/d253a55d-b9ad-4ede-b994-50c01467ad29)
![Screenshot_20230816_151307](https://github.com/acdh-oeaw/viecpro-nuxt/assets/48437174/ae5ee52b-06cc-414b-9f3f-785d370fd75e)
